services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      # Descomenta si quieres carpeta de backups en host:
      # - ./backups:/var/opt/mssql/backup
    restart: unless-stopped
volumes:
  mssql_data:
